//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monetov_Hospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Monetov_Hospital1Entities1 : DbContext
    {
        public Monetov_Hospital1Entities1()
            : base("name=Monetov_Hospital1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<description_of_operation> description_of_operation { get; set; }
        public virtual DbSet<medical_history> medical_history { get; set; }
        public virtual DbSet<operation> operation { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<patient_condition> patient_condition { get; set; }
        public virtual DbSet<permissions> permissions { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<treatment_sheet> treatment_sheet { get; set; }
        public virtual DbSet<type_of_treatment> type_of_treatment { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<worker> worker { get; set; }
    }
}
