//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monetov_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_history
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medical_history()
        {
            this.doctor = new HashSet<doctor>();
            this.patient = new HashSet<patient>();
        }
    
        public int medical_history_ID { get; set; }
        public string diagnosis { get; set; }
        public System.DateTime date_of_the_disease { get; set; }
        public int operation_code { get; set; }
        public System.DateTime date_of_cure { get; set; }
        public int type_of_treatment_ID { get; set; }
        public int treatment_sheet_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctor> doctor { get; set; }
        public virtual treatment_sheet treatment_sheet { get; set; }
        public virtual type_of_treatment type_of_treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patient { get; set; }
    }
}
