//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monetov_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_history
    {
        public int medical_history_ID { get; set; }
        public string diagnosis { get; set; }
        public System.DateTime date_of_the_disease { get; set; }
        public int operation_code { get; set; }
        public System.DateTime date_of_cure { get; set; }
        public int type_of_treatment_ID { get; set; }
        public int treatment_sheet_ID { get; set; }
    
        public virtual treatment_sheet treatment_sheet { get; set; }
        public virtual type_of_treatment type_of_treatment { get; set; }
    }
}
