//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monetov_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class operation
    {
        public int operation_ID { get; set; }
        public System.DateTime date_of_operation { get; set; }
        public bool result { get; set; }
        public int description_of_operation_ID { get; set; }
    
        public virtual description_of_operation description_of_operation { get; set; }
    }
}
