//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monetov_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int patient_ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string middle_name { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public bool gender { get; set; }
        public string town { get; set; }
        public int operation_ID { get; set; }
        public int medical_history_ID { get; set; }
        public Nullable<int> role_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual medical_history medical_history { get; set; }
        public virtual operation operation { get; set; }
        public virtual roles roles { get; set; }
        public virtual users users { get; set; }
    }
}
