//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monetov_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment_sheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public treatment_sheet()
        {
            this.medical_history = new HashSet<medical_history>();
        }
    
        public int treatment_sheet_ID { get; set; }
        public string pressure { get; set; }
        public System.DateTime treatment_date { get; set; }
        public string medicine { get; set; }
        public decimal temperature { get; set; }
        public int patient_condition_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medical_history> medical_history { get; set; }
        public virtual patient_condition patient_condition { get; set; }
    }
}
